### ISSUE TITLE
How to evaluate I(W)

### ISSUE THREAD

**Issue by ylwangy** [ysw1021/AGG#2]

**Comment by ylwangy** [comment]
Hi, thanks for your great work and open resources.

Is there any evaluation implementation by using the I(W) score in the paper?

Thanks

**Comment by ysw1021** [comment]
Hi,

you can implement the evaluation of I(W) score by extracting embedding matrix from learned Transformer model and using svd function of Pytorch.

Below is the code to calculate I(W) given embedding matrix W

```
u, s, v = torch.svd(W)
z = torch.exp(torch.matmul(W,v)).sum(0)
i_w = z.min()/z.max()
```

Thanks
